from urllib import request
from bs4 import BeautifulSoup
import re
sichuan =  ["阿寨","埃岱","安德","安靖","广汉北","巴中",
    "白果",
    "白石岩",
    "百里峡",
    "柏村",
    "碑木镇",
    "彭山北",
    "苍溪",
    "朝天南",
    "成都",
    "达州",
    "大山铺",
    "大英东",
    "代湾",
    "德昌",
    "德阳",
    "都江堰",
    "渡市",
    "峨边",
    "峨眉",
    "峨眉山",
    "尔赛河",
    "甘洛",
    "共和",
    "关村坝",
    "广安",
    "广元",
    "红光镇",
    "汉源",
    "红峰",
    "花棚子",
    "华蓥",
    "简阳",
    "简阳南",
    "江油",
    "金口河",
    "敬梓场",
    "青城山",
    "开江",
    "孔滩",
    "拉白",
    "拉鲊",
    "阆中",
    "乐山",
    "乐武",
    "乐跃",
    "离堆公园",
    "李市镇",
    "联合乡",
    "凉红",
    "刘沟",
    "隆昌",
    "罗江东",
    "毛坝",
    "茅草坪",
    "眉山",
    "眉山东",
    "米易",
    "绵阳",
    "冕宁",
    "冕山",
    "内江",
    "南部",
    "南充",
    "南尔岗",
    "尼波",
    "尼日",
    "攀枝花",
    "彭州",
    "蓬安",
    "郫县",
    "郫县西",
    "平昌",
    "蒲坝",
    "普雄",
    "青白江东",
    "青莲",
    "青神",
    "渠县",
    "三汇镇",
    "沙马拉达",
    "沙湾",
    "上普雄",
    "双凤驿",
    "双流机场",
    "双流西",
    "苏雄",
    "遂宁",
    "铁口",
    "铁西",
    "桐子林",
    "土溪",
    "瓦祖",
    "弯坵",
    "万源",
    "王场",
    "武胜",
    "西昌",
    "犀浦",
    "喜德",
    "下普雄",
    "小儿坪",
    "谢家镇",
    "新都东",
    "新江",
    "新津",
    "新凉",
    "宣汉",
    "燕岗",
    "杨漩",
    "一步滩",
    "宜宾",
    "迤资",
    "迎宾路",
    "迎祥街",
    "营山",
    "永郎",
    "俞冲",
    "月华",
    "岳池",
    "越西",
    "枣子林",
    "轸溪",
    "竹园坝",
    "资阳",
    "资中",
    "自贡"]
def main():
    global sichuan
    print(len(sichuan))
    for item in sichuan:
        print(item)
    # html = request.urlopen("http://www.oklx.com/cn/train/province/db56dd5d0177.html")
    # print(html.read())
    # bs_obj = BeautifulSoup(html, "lxml",from_encoding='utf-8')
    # res_list = bs_obj.findAll(name='a',attrs={"id":re.compile("ctl00_ContentPlaceHolder1_DataList1_ctl[0-9][0-9]_DataList2_ctl[0-9][0-9]_HyperLink1")})
    # for res in res_list:
    #     print()
    #     print(res.getText())
    # ctl00_ContentPlaceHolder1_DataList1_ctl00_DataList2_ctl00_HyperLink1
    # ctl00_ContentPlaceHolder1_DataList1_ctl01_DataList2_ctl01_HyperLink1
if __name__ == '__main__':
    main()


